/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./accounts/*.php",
    "./ajax/*.php",
    "./db/*.php",
    "./js/*.js",
    "./pages/*.php",
    "./src/*.php",
    "./templates/*.php",
    "./test/*.php",
    "./websocket/*.{html,js,php}",
  ],
  safelist: [
    'bg-lose',
    'text-online',
    'text-offline',
    'text-yellow-400',
    'text-darker',
    'text-dark',
    'z-[9]',
    'z-[8]',
    'z-[7]',
    'z-[6]',
    '-mt-[54px]',
    '-mt-[68px]',
    'min-w-[18rem]',
    'animation-shake',
    {
      pattern: /text-(silver|gold|bronze|platinum|iron|emerald|diamond|master|grandmaster|challenger)\/100/,
    },
    {
      pattern: /text-(threat-xxs|threat-xs|threat-s|threat-m|threat-l|threat-xl|threat-xxl)\/100/,
    },
    {
      pattern: /decoration-(red-700|green-800|blue-800|pink-700|lime-500|cyan-600|amber-600|yellow-400|purple-700|rose-400)/,
    },
    {
      pattern: /text-(red-700|green-800|blue-800|pink-700|lime-500|cyan-600|amber-600|yellow-400|purple-700|rose-400)\/100/,
    },
    {
      pattern: /bg-(tag-red|tag-yellow|tag-blue|tag-orange|tag-cyan|tag-pink|tag-green|tag-lime|tag-navy|tag-purple)\/100/,
    },
  ],
  theme: {
    extend: {
      colors: {
        'iron': '#392b28',
        'bronze': '#cd8d7f',
        'silver': '#99a0b5',
        'gold': '#d79c5d',
        'platinum': '#77c9d9',
        'emerald': '#46a678',
        'diamond': '#6487c1',
        'master': '#b160f3',
        'grandmaster': '#cd423a',
        'challenger': '#52cfff',
        'tag-red': '#751C1C',
        'tag-yellow': '#9b8e03',
        'tag-blue': '#1C5875',
        'tag-orange': '#b1640a',
        'tag-cyan': '#1C7556',
        'tag-pink': '#6d0958',
        'tag-green': '#264b0e',
        'tag-lime': '#185504',
        'tag-navy': '#2E1C75',
        'tag-purple': '#5B1C75',
        'tag-positive': '#0a291a',
        'tag-negative': '#280b1a',
        'threat-xxs': '#dddddd',
        'threat-xs': '#e1c1c1',
        'threat-s': '#ea8a8a',
        'threat-m': '#f25353',
        'threat-l': '#f73737',
        'threat-xl': '#fbc1c1',
        'threat-xxl': '#ff0000',
        'lose': '#3c000f80',
        'mid': '#2d364f80',
        'middle': '#21263a',
        'searchbg': '#191b2d',
        'searchtitle': '#242845',
        'win': '#003c0f80',
        'offline': '#b31414',
        'online': '#1aa23a',
        'light': '#2a2d40',
        'dark' : '#141624',
        'darker': '#0e0f18',
        'whiteblue': '#ccd0eb',
        'loading': '#565656',
        'loading-light': '#acacac',
      },
      gridTemplateColumns: {
        'topbartwok': '25% 328px auto 328px 25%',
        'topbarfullhd': 'calc((100vw - 1172px)/2) 328px 420px 328px calc((100vw - 1172px)/2)',
      },
      gridTemplateRows: {
        'teaminfo': '4rem auto',
      },
      keyframes: {
        slideAndFadeIn: {
          '0%': { transform: 'translateY(-1rem)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        moveUpAndFadeOut: {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(-10px)', opacity: '0' },
        },
        shake: {
          '0%': { transform: 'translate(2px, 1px) rotate(0deg)' },
          '10%': { transform: 'translate(-1px, -2px) rotate(-1deg)' },
          '20%': { transform: 'translate(-3px, 0px) rotate(1deg)' },
          '30%': { transform: 'translate(0px, 2px) rotate(0deg)' },
          '40%': { transform: 'translate(1px, -1px) rotate(1deg)' },
          '50%': { transform: 'translate(-1px, 2px) rotate(-1deg)' },
          '60%': { transform: 'translate(-3px, 1px) rotate(0deg)' },
          '70%': { transform: 'translate(2px, 1px) rotate(-1deg)' },
          '80%': { transform: 'translate(-1px, -1px) rotate(1deg)' },
          '90%': { transform: 'translate(2px, 2px) rotate(0deg)' },
          '100%': { transform: 'translate(1px, -2px) rotate(-1deg)' },
        },
      },
      animation: {
        'slideAndFadeIn': '.5s ease-in-out 0s 1 slideAndFadeIn',
        'fadeIn': '.5s ease-in-out 0s 1 fadeIn',
        'moveUpAndFadeOut': 'moveUpAndFadeOut 1s ease-in-out',
        'shake': 'shake 0.3s 1 ease-out',
      },
    },
    screens: {
      'hd': '721px',
      'fullhd': '1281px',
      'twok': '1921px',
    },
  },
  plugins: [],
}
